docs_dir:         "docs"

site_name:        "Qtilities"
site_author:      "Qtilities Organization"
site_url:         "https://qtilities.github.io"
site_dir:         "_site"
site_description: "Qtilities website"

repo_name:        "GitHub"
repo_url:         "https://github.com/qtilities/website"
edit_uri:         "edit/master/docs/"
remote_branch:    "www"

extra:
  site_web_author: "Qtilities Organization"
  repo_owner_url:  "https://github.com/qtilities"
  repo_branch:     "master"

  cards:          "data/layout/cards.yml"
  nav:            "data/layout/navigation.yml"
  social:         "data/social.yml"

markdown_extensions:
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
    alt: short
    options:
      attributes:
        align: absmiddle
        height: 20px
        width: 20px
hooks:
- scripts/hooks.py

plugins:
  search: {}
# FIXME: conflicts with # prefixed HTML unicode characters, see
#        https://github.com/theskumar/autolink-references-mkdocs-plugin/issues/7
# autolink_references:
#   autolinks:
#   - reference_prefix: '#'
#     target_url: "https://github.com/sfztools/sfizz/issues/<num>"
  blogging:
    dirs:
    - "news/posts"
    locale: "en"
    full_content: true
    paging: true
    show_total: false
    size: 5
    template: "layout/blogging-plugin.html"
    meta_time_format: "%Y-%m-%d %H:%M:%S"
    time_format: "%Y-%m-%d %H:%M:%S"
  exclude: # TODO: to remove when 1.5 comes out
    glob:
    - "*.j2"
    - "info.md"

theme:
  name:        null
  custom_dir: "layout"
  highlightjs: true
  hljs_light: "github"
  hljs_dark:  "github-dark-dimmed"
  nav_style:  "dark"
  locale:     "en"
  bootstrap_version: "5.3.0"
  favicons:
    apple_touch_icon_size: "180x180"
    msapp_tilecolor: "#da532c"
    theme_color: "#ffffff"
  shortcuts:
    help:     191 # ?
    next:      78 # n
    previous:  80 # p
    search:    83 # s

watch:
- data
- docs
- layout
